### ISSUE TITLE
Cannot use text base browsers

### ISSUE THREAD

**Issue by ograycode** [jarun/ddgr#63]
When I try to use a text based browser (w3m or lynx) I receive the following error `[ERROR] register() takes from 2 to 3 positional arguments but 4 were given`. It does work with gui based browsers though.

Operating system: macOS High Sierra v10.13.6

I tried this on both normal bash/terminal and on zsh and got the same results.

w3m version:
```
➜  w3m -version
w3m version w3m/0.5.3+git20180125, options lang=en,m17n,color,ansi-color,mouse,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,ipv6,alarm,mark
```

ddgr version:
```
➜  ddgr --version
1.4
```

query and command output:
```
➜  BROWSER=w3m ddgr django decorator require_post

 (1) View decorators | Django documentation | Django  [docs.djangoproject.com]
The decorators in django.views.decorators.http can be used to restrict access to views based on the ... require_POST()¶ Decorator to require that a view only accepts ...

 (2) Working with Django View Decorators - Simple is Better Than ...  [simpleisbetterthancomplex.com]
View decorators can be used to restrict access to certain views. Django come with some built-in decorators, like login_required, require_POST or has_permissi...

 (3) django.views.decorators.http | Django documentation | Django  [docs.djangoproject.com]
Source code for django.views.decorators.http ... require_POST. __doc__ = "Decorator to require that a view only ... archives of the django-users mailing list, or post ...

 (4) Decorator overwriting POST, GET and REQUEST in Django - doing ...  [stackoverflow.com]
In Django, I have created a function decorator which can - in this example - create a lowercase version of a supplied POST/GET argument, and it updates the REQUEST before the view
handles it all. ...

 (5) Creating class based view decorators using simple Django ...  [www.daveoncode.com]
For example let's consider we have a view that require a POST ... and this is the class decorator implementation: from django.views.decorators.http import ...

 (6) How to display a custom error page for HTTP status 405 ...  [stackoverflow.com]
My question is simple, how do I display a custom error page for HTTP status 405 (method not allowed) in Django when using the @require_POST decorator? I'm using the
django.views.decorators.http.

 (7) View decorators — Django 1.10 documentation  [django-document-korean.readthedocs.io]
The decorators in django.views.decorators.http can be used to restrict access to views based on the ... require_POST()¶ Decorator to require that a view only accepts ...

 (8) View decorators — Django 2.2.dev20180622141950 documentation  [django.readthedocs.io]
The decorators in django.views.decorators.http can be used to restrict access to views based on the ... require_POST ¶ Decorator to require that a view only accepts ...

 (9) How to secure your Django project by validating incoming ...  [www.twilio.com]
In this guide we'll cover how to secure your Django application by validating incoming requests to your Twilio webhooks are, in fact, from Twilio. With a few lines of code we'll
write a custom decorator for our Django project that uses the Twilio Python SDK's validator utility. We can then ...

 (10) Writing Django Views: Function Based Views ... - Program Everyday  [programeveryday.com]
Writing Django Views: Function Based Views, ... In FBVs I typically import django.views.decorators.http.require_POST and use that as a decorator to specify that the ...

ddgr (? for help) 1
[ERROR] register() takes from 2 to 3 positional arguments but 4 were given
```

Thanks for your hard work, and if there's anything I can do to help resolve this issue, let me know.

**Comment by jarun** [comment]
What is the python version?

Also, do you see the same issue with other text based browsers?

**Comment by ograycode** [comment]
python version: `3.7.0`. I modified ddgr to print the stack trace. here it is:

```
➜  BROWSER=lynx ddgr -d django decorator request_post

3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]
[DEBUG] ddgr version 1.4
[DEBUG] Python version 3.7.0
[DEBUG] q:django decorator request_post, region:us-en, page:0, curindex:1, safe:1
[DEBUG] nextParams:
[DEBUG] proxy:{'https': None}
[DEBUG] Response body written to '/var/folders/f6/hhst1sf11wd0cy25krt4t6sw0000gn/T/ddgr-response-3bwxd8ol'.
[DEBUG] Prev nextParams:
[DEBUG] Next nextParams: Keywords=django%20decorator%20request_post&xargs=12KPjg1pZSrp68i%2D%5FoMPCRErjGnQNVmZ615JIuTcQ%5FQZAD6A5dYdR%5FePqBypItDrUtu0KJk6nQo%5FpPIfD7ucu6&hData=12KPjg1qdOxJy7tuqnF9W2SOOj8m4%2E

 (1) Decorator overwriting POST, GET and REQUEST in Django - doing ...  [stackoverflow.com]
In Django, I have created a function decorator which can - in this example - create a lowercase version of a supplied POST/GET argument, and it updates the REQUEST before the view handles it all. ...

 (2) Working with Django View Decorators - Simple is Better Than ...  [simpleisbetterthancomplex.com]
View decorators can be used to restrict access to certain views. Django come with some built-in decorators, like login_required, require_POST or has_permissi...

 (3) View decorators | Django documentation | Django  [docs.djangoproject.com]
View decorators¶ Django provides several decorators that can be applied ... Note that request methods should ... require_POST()¶ Decorator to require that a view ...

 (4) django - request.POST.get('sth') vs request.POST['sth ...  [stackoverflow.com]
What is the difference between request.POST.get('sth') ... Update request.POST or request.GET using a view decorator. 0. ... django: request.POST key is empty if the ...

 (5) How to Add reCAPTCHA to a Django Site - Simple is Better Than ...  [simpleisbetterthancomplex.com]
How to Add reCAPTCHA to a Django Site. Feb 21, ... an alternative using requests and also an implementation using decorators, ... form = CommentForm (request. POST) ...

 (6) Working with URL, GET, POST parameters in Django  [django.cowhite.com]
This tutorial tries to clarify on how one can pass parameters from one page to another page in Django.

 (7) How to secure your Django project by validating incoming ...  [www.twilio.com]
In this guide we'll cover how to secure your Django application by validating incoming requests to your Twilio webhooks are, in fact, from Twilio. With a few lines of code we'll write a custom decorator for our Django project that uses the Twilio Python SDK's validator utility. We can then ...

 (8) Using the Django authentication system | Django documentation ...  [docs.djangoproject.com]
Using the Django authentication system¶. This document explains the usage of Django's authentication system in its default configuration. This configuration has evolved to serve the most common project needs, handling a reasonably wide range of tasks, and has a careful implementation of passwords and permissions.

 (9) Requests - Django REST framework  [www.django-rest-framework.org]
Django, API, REST, Requests. ... This is similar to the standard request.POST and request ... The APIView class or @api_view decorator will ensure that this property ...

 (10) 2 - Requests and responses - Django REST framework  [www.django-rest-framework.org]
Django, API, REST, 2 - Requests and responses. ... which is similar to request.POST, ... The @api_view decorator for working with function based views.

ddgr (? for help) 1
[DEBUG] Opening https://stackoverflow.com/questions/9093299/decorator-overwriting-post-get-and-request-in-django-doing-it-right
Traceback (most recent call last):
  File "/usr/local/bin/ddgr", line 1813, in <module>
    main()
  File "/usr/local/bin/ddgr", line 1802, in main
    repl.cmdloop()
  File "/usr/local/bin/ddgr", line 1513, in cmdloop
    open_url(self._urltable[str(i)])
  File "/usr/local/bin/ddgr", line 111, in open_url
    browser = webbrowser.get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 42, in get
    register_standard_browsers()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

I suspect it may be a bug in python and/or a python + platform specific issue as I can recreate it with python's standard library:

```
➜  BROWSER=lynx python3

Python 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> webbrowser.register_standard_browsers()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

>>> webbrowser._browsers
{'macosx': [None, <webbrowser.MacOSXOSAScript object at 0x10df412e8>], 'chrome': [None, <webbrowser.MacOSXOSAScript object at 0x10df41358>], 'firefox': [None, <webbrowser.MacOSXOSAScript object at 0x10df485c0>], 'safari': [None, <webbrowser.MacOSXOSAScript object at 0x10df48b70>], 'lynx': [None, <webbrowser.GenericBrowser object at 0x10e014198>]}

>>> webbrowser._browsers['lynx'].open('http://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'list' object has no attribute 'open'
>>> webbrowser._browsers['lynx'][1].open('http://google.com')
```

Interestingly enough, `webbrowser._browsers['lynx'][1].open('http://google.com')` worked.

**Comment by jarun** [comment]
ddgr is not tested against python 3.7.0 against. I think there has been some change in the related python module which would get uncovered once ddgr is tested against it.

**Comment by ograycode** [comment]
@jarun gotcha. At this point, I believe it's a bug with python 3.7 (and probably specific to mac). It appears there are a few bugs using a mac and using BROWSER. See https://bugs.python.org/issue31348 and https://bugs.python.org/issue24955

I'll open an issue with python as it's very easy to reproduce.

**Comment by jarun** [comment]
:+1: I am leaving the current defect open. Please close when it is fixed in Python 3.7.

**Comment by jarun** [comment]
@ograycode is this fixed yet?

**Comment by ograycode** [comment]
@jarun The bug reported here is fixed, but it hasn't been released. According to the [pep](https://www.python.org/dev/peps/pep-0537/#maintenance-releases) the 3.7.1 release should be coming soon.

Until then, users can modify their local python install to include the fix.

**Comment by jarun** [comment]
We will wait till it's fixed in the release.

**Comment by jarun** [comment]
This is fixed at https://github.com/python/cpython/pull/7267.
